export function buildHelpText(version: string): string {
  return [
    `Agentix v${version}`,
    "",
    "Usage:",
    "  agentix <command>",
    "",
    "Commands:",
    "  help, --help, -h     show this help",
    "  version              print the installed version",
    "  server               start the backend bridge/API and inbox server",
    "                       flags: --port <n> --bridge-port <n> --host <addr>",
    "  dashboard            start the web control surface only",
    "                       flags: --port <n> --host <addr>",
    "  ui, web              aliases for dashboard",
    "  gateway              inspect or manage gateway integrations",
  "  logs                 print recent runtime logs",
  "  doctor               run backend diagnostics",
  "  usage                print backend runtime usage counts",
  "  config               inspect or set backend runtime config",
  "  sessions             list/create/inspect/delete backend sessions",
  "  memory               inspect/search/consolidate/reset backend memory",
  "  cron, scheduler      manage Agentix scheduled jobs",
  "  plans, plan          inspect Symphony plan executions",
    "  tasks, task          list tasks or inspect/control one task",
    "  approvals, approval  list approvals or approve/reject one task",
    "  search               search tasks, sessions, memory, audit, logs, jobs",
    "  audit                list audit entries or inspect one entry",
    "  healing              inspect/promote/deprecate healing procedures",
    "  support              create a support bundle",
    "  mods                 list available tools/modules",
    "  plugin, extension    alias for mods",
    "  eval, broadcast      run a stimulus directly through the backend",
    "  shell                explain how to open the interactive shell",
    "",
    "See README.md for the Hermes shell, setup wizard, update flow, cron, gateway, and dashboard details.",
  ].join("\n");
}
