export const openApiSpec = {
  openapi: "3.1.0",
  info: {
    title: "Agentix Backend API",
    version: "2.1.0",
    description: "Agentix control API for Powerhouse, Symphony, Pi agents, memory, approvals, scheduler, gateways, and support diagnostics.",
  },
  servers: [
    { url: "http://127.0.0.1:3000", description: "Inbox/dashboard server" },
    { url: "http://127.0.0.1:3456", description: "Bridge server" },
  ],
  security: [{ bearerAuth: [] }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        description: "Required when AGENTIX_SESSION_TOKEN is configured.",
      },
    },
  },
  paths: {
    "/health": { get: { security: [], summary: "Health check" } },
    "/openapi.json": { get: { security: [], summary: "OpenAPI contract" } },
    "/doctor": { get: { summary: "Runtime diagnostics" } },
    "/usage": { get: { summary: "Runtime usage counters and status breakdowns" } },
    "/config": {
      get: { summary: "Read redacted runtime config" },
      post: { summary: "Update allowed non-secret runtime config values" },
    },
    "/execute": { post: { summary: "Execute a stimulus through Powerhouse/Symphony/Pi agents" } },
    "/execute/stream": { post: { summary: "Execute a stimulus with server-sent event streaming" } },
    "/sessions": {
      get: { summary: "List sessions" },
      post: { summary: "Create session" },
    },
    "/sessions/{id}": {
      get: { summary: "Inspect session" },
      delete: { summary: "Delete session" },
    },
    "/sessions/{id}/rename": { post: { summary: "Rename session" } },
    "/sessions/prune": { post: { summary: "Prune old sessions" } },
    "/sessions/optimize": { post: { summary: "Optimize session storage" } },
    "/memory": { get: { summary: "List memory records" } },
    "/memory/search": { get: { summary: "Search memory" } },
    "/memory/consolidate": { post: { summary: "Consolidate memory" } },
    "/memory/reset": { post: { summary: "Reset memory records" } },
    "/tools": { get: { summary: "List registered Pi agents/tools" } },
    "/tools/{id}": { get: { summary: "Inspect Pi agent/tool" } },
    "/tasks": { get: { summary: "List tasks" } },
    "/tasks/{id}": { get: { summary: "Inspect task" } },
    "/tasks/{id}/action": { post: { summary: "Cancel, retry, or restart task" } },
    "/approvals": { get: { summary: "List pending approvals" } },
    "/approvals/{id}": { get: { summary: "Inspect approval" } },
    "/approvals/{id}/approve": { post: { summary: "Approve task" } },
    "/approvals/{id}/reject": { post: { summary: "Reject task" } },
    "/plans": { get: { summary: "List Symphony plan executions" } },
    "/plans/{id}": { get: { summary: "Inspect Symphony plan execution" } },
    "/plans/{id}/action": { post: { summary: "Replay, cancel, or retry failed tasks for a Symphony plan" } },
    "/audit": { get: { summary: "List audit entries" } },
    "/audit/{id}": { get: { summary: "Inspect audit entry" } },
    "/logs": { get: { summary: "List runtime logs" } },
    "/logs/{index}": { get: { summary: "Inspect runtime log entry" } },
    "/healing/stats": { get: { summary: "List healing failures and procedures" } },
    "/healing/detail/{id}": { get: { summary: "Inspect healing failure or procedure" } },
    "/healing/procedures/{id}/promote": { post: { summary: "Promote healing procedure" } },
    "/healing/procedures/{id}/deprecate": { post: { summary: "Deprecate healing procedure" } },
    "/scheduler/jobs": {
      get: { summary: "List scheduled jobs" },
      post: { summary: "Create scheduled job" },
    },
    "/scheduler/jobs/{id}": {
      get: { summary: "Inspect scheduled job" },
      post: { summary: "Update scheduled job" },
      delete: { summary: "Delete scheduled job" },
    },
    "/scheduler/jobs/{id}/run": { post: { summary: "Run scheduled job now" } },
    "/scheduler/jobs/{id}/enable": { post: { summary: "Enable scheduled job" } },
    "/scheduler/jobs/{id}/disable": { post: { summary: "Disable scheduled job" } },
    "/scheduler/run-due": { post: { summary: "Run due scheduled jobs" } },
    "/gateway": { get: { summary: "List gateways" } },
    "/gateway/{id}": { get: { summary: "Inspect gateway" } },
    "/gateway/{id}/enable": { post: { summary: "Enable gateway" } },
    "/gateway/{id}/disable": { post: { summary: "Disable gateway" } },
    "/gateway/{id}/message": { post: { summary: "Inject gateway message" } },
    "/search": { get: { summary: "Search runtime records" } },
    "/support/bundle": { post: { summary: "Create support bundle" } },
    "/events": { get: { summary: "Runtime event stream" } },
  },
} as const;
